const SUBF2M_LANGUAGE_MAP: Record<string, string> = {
  en: 'english',
  english: 'english',
  ar: 'arabic',
  arabic: 'arabic',
  es: 'spanish',
  spanish: 'spanish',
  fr: 'french',
  french: 'french',
  de: 'german',
  german: 'german',
  pt: 'portuguese',
  portuguese: 'portuguese',
  ru: 'russian',
  russian: 'russian',
  tr: 'turkish',
  turkish: 'turkish',
  it: 'italian',
  italian: 'italian',
  nl: 'dutch',
  dutch: 'dutch',
  ko: 'korean',
  korean: 'korean',
  ja: 'japanese',
  japanese: 'japanese',
  zh: 'chinese',
  chinese: 'chinese',
  fa: 'farsi',
  farsi: 'farsi',
  ur: 'urdu',
  urdu: 'urdu',
  hi: 'hindi',
  hindi: 'hindi',
  bn: 'bengali',
  bengali: 'bengali',
  id: 'indonesian',
  indonesian: 'indonesian',
  vi: 'vietnamese',
  vietnamese: 'vietnamese',
  th: 'thai',
  thai: 'thai',
  sv: 'swedish',
  swedish: 'swedish',
  da: 'danish',
  danish: 'danish',
  fi: 'finnish',
  finnish: 'finnish',
  no: 'norwegian',
  norwegian: 'norwegian',
  pl: 'polish',
  polish: 'polish',
  he: 'hebrew',
  hebrew: 'hebrew',
  el: 'greek',
  greek: 'greek',
  hu: 'hungarian',
  hungarian: 'hungarian',
  ro: 'romanian',
  romanian: 'romanian',
  bg: 'bulgarian',
  bulgarian: 'bulgarian',
  hr: 'croatian',
  croatian: 'croatian',
  sr: 'serbian',
  serbian: 'serbian',
  uk: 'ukrainian',
  ukrainian: 'ukrainian',
  ms: 'malay',
  malay: 'malay',
  my: 'burmese',
  burmese: 'burmese',
  ku: 'kurdish',
  kurdish: 'kurdish',
  mk: 'macedonian',
  macedonian: 'macedonian',
  ml: 'malayalam',
  malayalam: 'malayalam',
  sl: 'slovenian',
  slovenian: 'slovenian',
  si: 'sinhala',
  sinhala: 'sinhala',
}

export function normalizeLanguageCode(lang: string): string {
  const normalized = lang.trim().toLowerCase()
  if (normalized === 'all' || normalized === '*') return 'all'
  return SUBF2M_LANGUAGE_MAP[lang.toLowerCase()] || lang.toLowerCase()
}
